<?xml version="1.0" encoding="utf-8"?>
<!--
  Copyright (c) Microsoft Corporation. All rights reserved.
  
  Licensed under the MIT license.
-->
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
	<PropertyGroup>
		<PowerAppsTargetsPath Condition="'$(PowerAppsTargetsPath)' == ''">$(MSBuildExtensionsPath)\Microsoft\VisualStudio\v$(VisualStudioVersion)\PowerApps</PowerAppsTargetsPath>
	</PropertyGroup>

	<Import Project="$(PowerAppsTargetsPath)\Microsoft.PowerApps.VisualStudio.Pcf.props" Condition="Exists('$(PowerAppsTargetsPath)\Microsoft.PowerApps.VisualStudio.Pcf.props')" />

	<PropertyGroup>
		<DefaultProjectTypeGuid>FAE04EC0-301F-11D3-BF4B-00C04F79EFBC</DefaultProjectTypeGuid>
		<ProjectTypeGuids>$(DefaultProjectTypeGuid);$(ProjectTypeGuids)</ProjectTypeGuids>
		<AppendTargetFrameworkToOutputPath Condition="'$(AppendTargetFrameworkToOutputPath)' == ''">false</AppendTargetFrameworkToOutputPath>
		<OutputPath Condition="'$(OutputPath)' == ''">$(MSBuildProjectDirectory)\out\controls</OutputPath>
		<TargetFrameworkVersion Condition="'$(TargetFrameworkVersion)' == ''">v4.6.2</TargetFrameworkVersion>
		<!--Remove TargetFramework when this is available in 16.1-->
		<TargetFramework Condition="'$(TargetFramework)' == ''">net462</TargetFramework>
		<AccelerateBuildsInVisualStudio Condition="'$(AccelerateBuildsInVisualStudio)' == ''">true</AccelerateBuildsInVisualStudio>
		<DebugSymbols Condition="'$(DebugSymbols)' == ''">false</DebugSymbols>
		<DebugType Condition="'$(DebugType)' == ''">none</DebugType>
		<_ExcludeNpmRunBuildInput>$(ExcludeNpmRunBuildInput);node_modules/**</_ExcludeNpmRunBuildInput>
	</PropertyGroup>

	<Import Project="./Shared.props/NoAssembly.props" />
</Project>