<Project Sdk="Microsoft.Build.NoTargets/3.7.56">
	<PropertyGroup>
		<TargetFrameworks>netstandard2.0</TargetFrameworks>
		<Description>Provides targets for dataverse PCF projects (.pcfproj).</Description>
		<PackageTags>MSBuild MSBuildSdk dataverse PowerPlatform</PackageTags>
		<PackageIcon>Logo.png</PackageIcon>
		<GeneratePackageOnBuild>true</GeneratePackageOnBuild>
		<PackageType>MSBuildSdk</PackageType>
		<SuppressDependenciesWhenPacking>true</SuppressDependenciesWhenPacking>
		<RepositoryUrl>https://github.com/albanian-xrm/CSDPROJ-SDK.git</RepositoryUrl>
		<RepositoryType>git</RepositoryType>
		<PackageLicenseFile>LICENSE</PackageLicenseFile>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<IncludeDefaultItems>false</IncludeDefaultItems>
	</PropertyGroup>

	<ItemGroup>
		<Content Include="Sdk/**" Pack="true" PackagePath="Sdk" />
		<Content Include="../Shared/NoAssembly.props" Link="Sdk/Shared/NoAssembly.props" Pack="true" PackagePath="Sdk/Shared/" />
		<Content Include="../Shared/NoAssembly.targets" Link="Sdk/Shared/NoAssembly.targets" Pack="true" PackagePath="Sdk/Shared/" />
	</ItemGroup>

	<ItemGroup>
	  <Content Include="Logo.png" Pack="true" PackagePath="\" />
	  <None Include="..\LICENSE" Pack="true" PackagePath="\" />
	  <None Include="README.md" Pack="true" PackagePath="\" />
	</ItemGroup>

	<ItemGroup>
		<TestProjectReference Include="../AlbanianXrm.CDSProj.Sdk.Tests/**/*.pcfproj" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Nerdbank.GitVersioning" Condition="!Exists('packages.config')">
			<PrivateAssets>all</PrivateAssets>
			<Version Condition="'$(ManagePackageVersionsCentrally)'!='true'">3.*</Version>
		</PackageReference>
	</ItemGroup>

	<Import Project="../Shared/LocalNugetPackageCacheForTests.targets" />
	<Import Project="../Shared/PreparePackageReleaseNotesFromFile.targets" />
	<Import Project="../Shared/UpdateTestProjectReferences.targets" />
</Project>
